### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by WorldMaker** [Doodle3D/clipper-js#1]
Would you be interested in integrating Typescript typings into your npm package if I were to provide a PR for that?

**Comment by peteruithoven** [comment]
That sounds great. 
We have no Typescript experience, that would work with separate [definition files](http://www.typescriptlang.org/docs/handbook/writing-declaration-files.html)? Which wouldn't influence people that don't use Typescript? 
Is this easier than adding them externally through Typings (TypeScript Definition Manager)?

**Comment by WorldMaker** [comment]
Right, I'd just be PRing the definition file I wrote (index.d.ts to match index.js) and a simple package.json change (add a "typings" key). Wouldn't impact people not using Typescript.

Typings is great and what I'm using already for managing some of my type definition files, but the Typescript community as a whole is in transition to get more (approaching all) type definition files directly into npm, some as new typings-only packages and others directly into upstream projects. It's always preferable to see those type definitions directly in the upstream packages and released within each published version to npm, rather than having to maintain a separate repository/npm package. So it's always useful to ask if a project will host their typings directly. (...and expected sometimes that projects will say no because it can mean a few more PRs every so often to keep typings in sync with code changes and that's a small bit of extra maintenance workload that some projects don't want. Hence the friendly ask here first rather than send a PR first.)

**Comment by peteruithoven** [comment]
Alright, that sounds fine. I'll close this issue.
