### ISSUE TITLE
Request: Performance Metrics

### ISSUE THREAD

**Issue by Undistraction** [Doodle3D/clipper-js#6]
Would be great to see some performance comparisons with the original in the README. Wouldn't need to be exhaustive, but some ballpark idea would be really helpful.

**Comment by casperlamboo** [comment]
Sorry for the extremely late response, as this is only a very small wrapper on the function calls of the original clipper library I don't really see how performance will be different.

If you want to test this an share your results I'd be happy to include the bench marks in the readme.
